adm/urls.py
from django.conf.urls import url
from django.urls import path
from adm import views

app_name = 'adm'
urlpatterns = [
    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^usuarios$', views.usuarios, name='usuarios'),
    url(r'^user$', views.AddUser.as_view(), name='adduser'),
    path('user/<int:pk>/change/', views.UserUpdate.as_view(), name='edituser'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='deluser'),
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('user/<id>/password/', views.user_change_password, name='password_user'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^locais$', views.locais, name='locais'),
    path('local/<int:pk>/change/', views.LocalUpdate.as_view(), name='editlocal'),
    path('local/<int:pk>/delete/', views.LocalDelete.as_view(), name='deletelocal'),
    url(r'^addlocal$', views.AddLocal.as_view(), name='addlocal'),

    url(r'^sensores$', views.sensores, name='sensores'),
    path('sensor/<int:pk>/change/', views.SensorUpdate.as_view(), name='editsensor'),
    path('sensor/<int:pk>/delete/', views.SensorDelete.as_view(), name='deletesensor'),
    url(r'^addsensor$', views.AddSensor.as_view(), name='addsensor'),
]

core/urls.py
from django.conf.urls import url
from core import views

urlpatterns = [
    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^climate/$', views.climate, name='climate'),
    url(r'^graphs/$', views.graphs, name='graphs')
]

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import login, logout
from user.forms import UserAdminCreationForm
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url(r'^entrar$', login,
                      {'template_name': 'user/login.html',
                       'extra_context': {'formup': UserAdminCreationForm}
                       }, name='login'),
                  url(r'^sair$', logout, {'next_page': 'login'}, name='logout'),
                  path('', include('core.urls')),
                  path('sensores/', include('sensor.urls', namespace='sensor', )),
                  path('adm/', include('adm.urls', namespace='adm')),
                  path('user/', include('user.urls', namespace='user')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sensor/urls.py
from django.conf.urls import url
from sensor import views
from django.urls import path

app_name = 'sensor'

urlpatterns = [
    # The home page
    path('list', views.sensores, name='list'),
    path('<int:id>', views.sensor, name='sensor'),
]

user/urls.py
from django.conf.urls import url
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    # The home page
    path('<slug>/change', views.Profile.as_view(), name='profile'),
    path('password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),


]

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from core.openweather.api_requests import *
from sensor.models import *
from random import randint
from datetime import datetime, timedelta
import math

# Create your views here.
@login_required
def index(request):
    #dados da primeira cidade
    _locals = Local.objects.filter(usuario=request.user.id)
    local = _locals.first()
    forecast = None
    if local:
        forecast = get_day_forecast(local.coord_NW_lat, local.coord_NW_lat)
    
    #grafico
    consumoDia = [[i, randint(100, 200)] for i in range(20)]
    print(consumoDia)
    return render(request, 'core/index.html', {'consumoDia':consumoDia, 'local':local, 'forecast':forecast})

@login_required
def climate(request):
    local_objs = Local.objects.filter(usuario=request.user.id)
    opened_places = []
    locais = []
    weekday = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo']
    for local in local_objs:
        lat, lon = local.coord_NW_lat, local.coord_NW_lat
        city, state = local.cidade, local.estado
        if [city, state] in opened_places:
            continue
        opened_places.append([city, state])
        local_data = {'cidade':city, 'estado':state, 'hora': datetime.now().strftime('%H:%M'), 'forecast':[]}
        forecast = get_5days_forecast(lat, lon)
        for i, day in enumerate(forecast['list'][::8]):
            dt = datetime.fromtimestamp(day['dt'])
            day_data = {
                'temperatura': day['main']['temp'],
                'descricao': day['weather'][0]['description'],
                'vento': day['wind']['speed'],
                'icone': get_icon_name(day['weather'][0]['id']),
                'dia': weekday[dt.weekday()]
            }
            if i > 0:
                day_data['temperatura'] = int (day_data['temperatura'])
                day_data['dia'] = day_data['dia'][:3]
            local_data['forecast'].append(day_data)
        locais.append(local_data)

    return render(request, 'core/climate.html', {'locais': locais})

def distance_between_coords(lat1, lon1, lat2, lon2):
    R = 6371 #metros
    delta_lat = abs(lat2-lat1)
    delta_lon = abs(lon2-lon1)

    a = math.sin(delta_lat/2) * math.sin(delta_lat/2) + \
        math.cos(lat1) * math.cos(lat2) * \
        math.sin(delta_lon/2) * math.sin(delta_lon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))

    return R * c

@login_required
def graphs(request):
    local_objs = Local.objects.filter(usuario=request.user.id)
    id = request.GET.get('id') or local_objs[0].id

    local_items = list(local_objs.values_list('nome','id'))
    local = Local.objects.filter(usuario=request.user.id, id=id)[0]
    date_past = datetime.now().date() - timedelta(days=30)
    hist_objs = Historico.objects

    graph_data = {
        'nome' : local.nome,
        'cidade': local.cidade,
        'estado': local.estado,
        'area': "{:.2f}".format(distance_between_coords(
            local.coord_NW_lat, local.coord_NW_long,
            local.coord_NW_lat, local.coord_SE_long
        ) * distance_between_coords(
            local.coord_NW_lat, local.coord_SE_long,
            local.coord_SE_lat, local.coord_SE_long
        )),
        'sensores': [],
        'idade': (datetime.now(hist_objs.all()[0].time.tzinfo) - hist_objs.all()[0].time).days
    }
    sensores = Sensor.objects.filter(local=local.id)
    for sensor in sensores:
        sensor_data = {
            'id': sensor.id
        }
        sensor_data['temp'] = list(hist_objs.filter(time__gte=date_past).values_list('time', 'temperatura'))
        sensor_data['umi_solo'] = list(hist_objs.filter(time__gte=date_past).values_list('time', 'umidade_solo'))
        sensor_data['umi_ar'] = list(hist_objs.filter(time__gte=date_past).values_list('time', 'umidade_ar'))
        for n in ['temp', 'umi_solo', 'umi_ar']:
            for i in range(len(sensor_data[n])):
                sensor_data[n][i] = [sensor_data[n][i][0].strftime('%m/%d-%H:%M'), sensor_data[n][i][1]]
        graph_data['sensores'].append(sensor_data)

    return render(request, 'core/graphs.html', {'local_items': local_items, 'local': graph_data})

core/templates/_partial/breadcrumb.html
<div class="bread-crumb">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li><i class="fa fa-sitemap"></i></li>
            {% for url, label in breadcrumbs %}
                <li class="breadcrumb-item">
                    {% ifnotequal forloop.counter breadcrumbs_total %}
                        <a href="{{ url }}">{{ label|safe }}</a>
                    {% else %}
                        {{ label|safe }}
                    {% endifnotequal %}
                    {% if not forloop.last %}
{#                        <span class="divider"></span>#}
                    {% endif %}
                </li>
            {% endfor %}
        </ol>
    </nav>
</div>

core/templates/_partial/footer.html
<div class="pull-right">
  Agrolytics - Chuhaskell Slim - Code Race 2018
</div>
<div class="clearfix"></div>

core/templates/_partial/sidebar.html
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="{% url 'index' %}" class="site_title"><i class="fa fa-leaf"></i> <span>Agrolytics</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
        <div class="profile_pic">
            {% if not request.user.dir_imagem %}
                <img src="/static/images/user.png" alt="..." class="img-circle profile_img">
            {% else %}
                <img src="{{ request.user.dir_imagem.url }}" alt="No Image" class="img-circle profile_img">
            {% endif %}
        </div>
        <div class="profile_info">
            <span>Bem-vindo</span>
            <h2>{{ request.user }}</h2>
        </div>
    </div>
    <!-- /menu profile quick info -->

    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            <ul class="nav side-menu">
                <li>
                    <a href="{% url 'index' %}">
                        <i class="fa fa-home"></i> Início
                    </a>
                </li>
                {% if request.user.is_staff %}
                    <li><a href="{% url 'adm:index' %}"><i class="fa fa-wrench"></i>Administrador</a>
                {% endif %}
                <li><a href="{% url 'sensor:list' %}"><i class="fa fa-list-alt"></i>Lista de Sensores</a>
                <li><a href="{% url 'graphs' %}"><i class="fa fa-area-chart"></i>Gráficos</a>
                <li><a href="{% url 'climate' %}"><i class="fa fa-cloud"></i>Clima e Tempo</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'logout' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
    <!-- /menu footer buttons -->
</div>

core/templates/_partial/top_navigation.html
<div class="nav_menu">
    <nav>
        <!--<div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>-->

        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                   aria-expanded="false">
                    <img src="
                            {% if request.user.dir_imagem %}{{ request.user.dir_imagem.url }}{% else %}/static/images/user.png{% endif %}"
                         alt="">{{ request.user.username }}
                    <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="{% url 'user:profile' request.user.username %}"><i class="fa fa-user pull-right" style="color: #24292e"></i> Perfil</a>
                    </li>
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right" style="color: #24292e"></i>
                        Sair</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</div>