adm/urls.py
from django.conf.urls import url
from django.urls import path
from adm import views

app_name = 'adm'
urlpatterns = [
    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^usuarios$', views.usuarios, name='usuarios'),
    url(r'^user$', views.AddUser.as_view(), name='adduser'),
    path('user/<int:pk>/change/', views.UserUpdate.as_view(), name='edituser'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='deluser'),
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('user/<id>/password/', views.user_change_password, name='password_user'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^locais$', views.locais, name='locais'),
    path('local/<int:pk>/change/', views.LocalUpdate.as_view(), name='editlocal'),
    path('local/<int:pk>/delete/', views.LocalDelete.as_view(), name='deletelocal'),
    url(r'^addlocal$', views.AddLocal.as_view(), name='addlocal'),

    url(r'^sensores$', views.sensores, name='sensores'),
    path('sensor/<int:pk>/change/', views.SensorUpdate.as_view(), name='editsensor'),
    path('sensor/<int:pk>/delete/', views.SensorDelete.as_view(), name='deletesensor'),
    url(r'^addsensor$', views.AddSensor.as_view(), name='addsensor'),
]

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import login, logout
from user.forms import UserAdminCreationForm
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url(r'^entrar$', login,
                      {'template_name': 'user/login.html',
                       'extra_context': {'formup': UserAdminCreationForm}
                       }, name='login'),
                  url(r'^sair$', logout, {'next_page': 'login'}, name='logout'),
                  path('', include('core.urls')),
                  path('sensores/', include('sensor.urls', namespace='sensor', )),
                  path('adm/', include('adm.urls', namespace='adm')),
                  path('user/', include('user.urls', namespace='user')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

adm/models.py
from django.db import models

# Create your models here.

adm/forms.py
# # -*- coding: utf-8 -*-

from django import forms

from sensor.models import *


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class LocalForm(BaseForm):

    class Meta:
        model = Local
        fields = '__all__'

class SensorForm(BaseForm):
    class Meta:
        model = Sensor
        fields = '__all__'

adm/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic.edit import *

from user.forms import *
from django.contrib.messages.views import SuccessMessageMixin

from .forms import *
from sensor.models import *

# password
# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from django.urls import reverse_lazy

@staff_member_required
def index(request):
    return render(request, 'adm/index.html', {'countUsuarios': User.objects.all().count(),
                                              'countLocais': Local.objects.all().count(),
                                              'countSensores': Sensor.objects.all().count()})

# USUARIOS
@staff_member_required
def usuarios(request):
    usuarios = User.objects.all()
    return render(request, 'adm/usuarios.html', {'usuarios': usuarios})


@method_decorator(staff_member_required, name='dispatch')
class AddUser(SuccessMessageMixin, CreateView):
    model = User
    success_url = '/'
    template_name = 'adm/crud.html'
    form_class = UserCreation
    success_message = 'Usuario criado'
    extra_context = {'title': 'Adicionar Usuário'}

    # def get_success_url(self):
    #     pass


@method_decorator(staff_member_required, name='dispatch')
class UserUpdate(SuccessMessageMixin, UpdateView):
    model = User
    template_name = 'adm/crud.html'
    success_message = 'Usuário Atualizado'
    form_class = UserUpdate
    success_url = '/adm/usuarios'
    extra_context = {'title': 'Editar Usuário'}


@method_decorator(staff_member_required, name='dispatch')
class UserDelete(SuccessMessageMixin, DeleteView):
    model = User
    success_url = reverse_lazy('adm:usuarios')
    success_message = 'Usuário Deletado'
    template_name = 'adm/confirm_delete.html'


@staff_member_required
def user_change_password(request, id):
    user = User.objects.get(id=id)
    if request.method == 'POST':
        form = PasswordForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Senha trocada com sucesso!')
            return redirect('adm:edituser', pk=user.id)
        else:
            messages.error(request, 'Por favor, corrija os erros abaixo.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'adm/crud.html', {
        'form': form,
        'title': 'Trocar senha ' + user.username
    })
############################


# Local
@staff_member_required
def locais(request):
    locais = Local.objects.all()
    context = {
        'locais': locais,
    }
    return render(request, 'adm/locais.html', context)


@method_decorator(staff_member_required, name='dispatch')
class AddLocal(SuccessMessageMixin, CreateView):
    model = Local
    form_class = LocalForm
    template_name = 'adm/crud.html'
    success_message = 'Local Adicionada'
    success_url = '/adm/locais'
    extra_context = {'title': 'Adicionar Local'}

    # def get_success_url(self):
    #     pass

@method_decorator(staff_member_required, name='dispatch')
class LocalUpdate(SuccessMessageMixin, UpdateView):
    model = Local
    form_class = LocalForm
    template_name = 'adm/crud.html'
    success_url = '/adm/locais'
    success_message = 'Local Atualizado'
    extra_context = {'title': 'Editar Local'}


@method_decorator(staff_member_required, name='dispatch')
class LocalDelete(SuccessMessageMixin, DeleteView):
    model = Local
    success_url = reverse_lazy('adm:locais')
    success_message = 'Local Deletado'
    template_name = 'adm/confirm_delete.html'


############################
@staff_member_required
def sensores(request):
    sensores = Sensor.objects.all()
    context = {
        'sensores': sensores,
    }
    return render(request, 'adm/sensores.html', context)


@method_decorator(staff_member_required, name='dispatch')
class AddSensor(SuccessMessageMixin, CreateView):
    model = Sensor
    form_class = SensorForm
    template_name = 'adm/crud.html'
    success_message = 'Sensor Adicionada'
    extra_context = {'title': 'Adicionar Sensor'}
    success_url = '/adm/sensores'

    # def get_success_url(self):
    #     pass

@method_decorator(staff_member_required, name='dispatch')
class SensorUpdate(SuccessMessageMixin, UpdateView):
    model = Sensor
    form_class = SensorForm
    template_name = 'adm/crud.html'
    success_message = 'Sensor Atualizado'
    extra_context = {'title': 'Editar Sensor'}
    success_url = '/adm/sensores'


@method_decorator(staff_member_required, name='dispatch')
class SensorDelete(SuccessMessageMixin, DeleteView):
    model = Sensor
    success_url = reverse_lazy('adm:Sensor')
    success_message = 'Sensor Deletado'
    template_name = 'adm/confirm_delete.html'


############################

adm/templates/adm/confirm_delete.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Confirme a remoção "{{ object }}":</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

adm/templates/adm/crud.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
{% endblock %}

{% block content %}
	<div class="x_panel">
    	<div class="x_title">
    		<h3>{{ title }}</h3>
    		<div class="clearfix"></div>
    	</div>
    	<div class="x_content">
    		<form method="post" enctype="multipart/form-data">{% csrf_token %}
		        {% include 'form.html' %}
		    </form>
    	</div>
    </div>
{% endblock content %}

adm/templates/adm/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Empresas {% endblock title %}

{% block stylesheets %}
    {{ block.super }}
{% endblock stylesheets %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
{% endblock %}

{% block content %}
   {% if request.user.is_staff %}
        <h3>Administração</h3>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="tile-stats">
                        <a href="{% url 'adm:usuarios' %}">
                            <div class="icon"><i class="fa fa-user"></i></div>
                            <div class="count">{{ countUsuarios }}</div>
                            <h3>Usuários</h3>
                            <p>Consultar ou cadastrar usários para localidades.</p>
                        </a>
                    </div>
                </div>
                <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <a href="{% url 'adm:locais' %}">
                        <div class="tile-stats">
                            <div class="icon"><i class="fa fa-home"></i></div>
                            <div class="count">{{ countLocais }}</div>
                            <h3>Locais</h3>
                            <p>Consultar ou cadastrar Localidades.</p>
                        </div>
                    </a>
                </div>
                <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <a href="{% url 'adm:sensores' %}">
                        <div class="tile-stats">
                            <div class="icon"><i class="fa fa-rss"></i></div>
                            <div class="count">{{ countSensores }}</div>
                            <h3>Sensores</h3>
                            <p>Consultar ou cadastrar municípios</p>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    {% endif %}


{% endblock content %}

{% block javascripts %}
    {{ block.super }}
{% endblock javascripts %}

adm/templates/adm/locais.html
{% extends "base.html" %}
{% load static %}
{% block title %} Empresas {% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    {% include "adm/_partial/dt-table-styles.html" %}
{% endblock stylesheets %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <!-- /dados relevantes-->
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Locais</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap"
                           cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>Pais/Estado</th>
                            <th>Cidade</th>
                            <th>Local</th>
                            <th>Responsável</th>
                            <th>Imagem</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for local in locais %}
                            <tr>
                                <td>{{ local.pais }}/{{ local.estado }}</td>
                                <td>{{ local.cidade }}</td>
                                <td>{{ local.nome }}</td>
                                <td>{{ local.usuario.nome }}</td>
                                {% if not local.dir_imagem %}
                                 <td style="text-align: center!important;">
                                    <img style="height: 150px" src="{% static 'images/empresa.png' %}"></td>
                                {% else %}
                                 <td style="text-align: center!important;">
                                    <img  style="height: 150px"  src="{{ local.dir_imagem.url }}"></td>
                                {% endif %}
                                <td align="center">
                                    <a href="">
                                        <button class="btn btn-xs btn-success"><i class="fa fa-level-down"></i> Entrar
                                        </button>
                                    </a>
                                    <a href="{% url 'adm:editlocal' local.id %}">
                                        <button class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> Editar
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <a href="{% url 'adm:addlocal' %}">
                <button class="btn btn-success"><i class="fa fa-plus"></i> Adicionar Local</button>
            </a>
        </div>

    </div>



{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    {% include "adm/_partial/scripts.html" %}
{% endblock javascripts %}

adm/templates/adm/sensores.html
{% extends "base.html" %}
{% load static %}
{% block title %} Empresas {% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    {% include "adm/_partial/dt-table-styles.html" %}
{% endblock stylesheets %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <!-- /dados relevantes-->
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Sensores</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap"
                           cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>Pais/Estado</th>
                            <th>Cidade</th>
                            <th>Responsavel</th>
                            <th>Local</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for sensor in sensores %}
                            <tr {% if sensor.status %}
                                    class="bg-green" style="color: black"
                                {% else %}
                                    class="bg-red" style="color: white"
                                {% endif %}>
                                <td>{{ sensor.local.pais }}/{{ sensor.local.estado }}</td>
                                <td>{{ sensor.local.cidade }}</td>
                                <td>{{ sensor.local.usuario }}</td>
                                <td>{{ sensor.local.nome }}</td>
                                <td align="center">
                                    <a href="">
                                        <button class="btn btn-xs btn-success"><i class="fa fa-level-down"></i> Entrar
                                        </button>
                                    </a>
                                    <a href="{% url 'adm:editsensor' sensor.id %}">
                                        <button class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> Editar
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <a href="{% url 'adm:addsensor' %}">
                <button class="btn btn-success"><i class="fa fa-plus"></i> Adicionar Sensor</button>
            </a>
        </div>

    </div>



{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    {% include "adm/_partial/scripts.html" %}
{% endblock javascripts %}

adm/templates/adm/usuarios.html
{% extends "base.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Usuários" "adm:usuarios" %}
{% endblock %}

{% block title %} Usuários do Sistema {% endblock title %}

{% block stylesheets %}
    {{ block.super }}
{% include "adm/_partial/dt-table-styles.html" %}
{% endblock stylesheets %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'adm:usuarios' %}">Usuários</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Usuários:
                        <small>setores disponíveis para: {{ andar.descricao }} </small>
                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap"
                           cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>Username</th>
                            <th>Nome</th>
                            <th>CPF</th>
                            <th>Email</th>
                            <th>Editar</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in usuarios %}
                            <tr>
                                <td>{{ user.username }}</td>
                                <td>{{ user.nome }}</td>
                                <td>{{ user.cpf }}</td>
                                <td>{{ user.email }}</td>
                                <td align="center">
                                    <a href="{% url 'adm:edituser' user.id %}">
                                        <button class="btn btn-xs btn-small btn-success"><i class="fa fa-pencil"></i> Editar</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'adm:adduser' %}">
         <button class="btn btn-success"><i class="fa fa-plus"></i> Adicionar Usuario</button>
    </a>
{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    {% include "adm/_partial/scripts.html" %}
{% endblock javascripts %}